general {
    hide_cursor = true
}

background {
    monitor =
    path = ~/.config/hypr/wallpapers/1.jpg
    blur_passes = 0
}

input-field {
  monitor =
  size = 40%, 10%
  font_family = DepartureMono Nerd Font
  dots_size = 20.0
  dots_text_format = *
  inner_color = rgba(0, 0, 0, 0.0)
  outline_thickness = 0
  check_color = rgba(0, 0, 0, 0.0)
  fail_color = rgba(0, 0, 0, 0.0)
  fail_text =
  dots_center = true
  font_color = rgba(245, 208, 152, 1)
  placeholder_text =
}
